version: "3.7"

x-base: &base
  restart: unless-stopped
  logging: 
    options:
      max-size: '50m'
      max-file: '3'
    driver: json-file

services:
  # Это наше классическое Rails-приложение
  web:
    <<: *base
    image: ruby:local
    working_dir: /home/app
    command: ["puma", "-w", "${WORKERS-1}", "-t", "${THREADS-1}:${THREADS-1}", "-p", "3000"]
    build:
      dockerfile: Dockerfile.ruby
    volumes:
      - ${PWD}/:/home/app
    ports:
      - 3000
    environment: {}
    labels:
      # если использовать Docker Provider для Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.rails.rule=Host(`rails.think`)"
      - "traefik.http.routers.rails.entrypoints=web"
      # если использовать Consul Catalog и регистрацию через consul registrator
      - "SERVICE_NAME=think/rails-web"
      - "SERVICE_TAGS=traefik.enable=true,\
        traefik.http.routers.rails-web.rule=Host(`rails.think`),\
        traefik.http.routers.rails-web.entrypoints=web,\
        monitoring,monitoring_hostname=local"
      

  traefik:
    <<: *base
    image: traefik:latest
    container_name: traefik
    network_mode: host
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.consulcatalog.endpoint.address=localhost:8500"
      - "--providers.consulcatalog.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--log.level=debug"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  consul:
    <<: *base
    image: consul:1.15
    container_name: consul
    network_mode: host
    command: ["consul", "agent",
      "-dev",
      "-node", "${HOSTNAME}",
      "-datacenter", "think",
      "-bootstrap-expect", "0",
      "-ui=true",
      "-bind=0.0.0.0", "-client=0.0.0.0", "-advertise=${CURRENT_IP}",
      "-log-level", "info"
    ]

  registrator:
    <<: *base
    image: gliderlabs/registrator:master
    network_mode: host
    command: -ip ${CURRENT_IP} -cleanup -ttl 40 -ttl-refresh 30 -resync 60 consul://localhost:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro


  victoriametrics:
    <<: *base
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.85.3
    command: ["-promscrape.config=/scrape.yml"]
    ports:
      - 8428:8428
      - 8089:8089
      - 8089:8089/udp
      - 2003:2003
      - 2003:2003/udp
      - 4242:4242
    volumes:
      - "${PWD}/scrape.yml:/scrape.yml:ro"
    labels:
      - "SERVICE_8428_NAME=think/vmui"
      - "SERVICE_8428_TAGS=traefik.enable=true,\
        traefik.http.routers.vmui.rule=Host(`vmui.think`),\
        traefik.http.routers.vmui.entrypoints=web"
